In [1]:
import sqlite3
import pandas as pd
import os

# 1. Definimos la ruta de trabajo
ruta = r"C:\Users\Yamil\OneDrive\Escritorio\Escritorio\Yamil\EBAC (CIENCIA DE DATOS)\Bloque 7 Análisis de datos con SQL\MOD 8 Consult comun SQL Python\Práctica"
os.chdir(ruta)

# 2. Leemos el CSV con pandas (es la forma más limpia y eficiente para crear la tabla)
df_rh = pd.read_csv("recursos_humanos.csv")

# 3. Creamos la conexión a la base de datos 
conn = sqlite3.connect("RH.db")

# 4. Volcamos el DataFrame a la tabla "Detalle"
# if_exists='replace' asegura que si corres la celda varias veces, no se dupliquen los datos.
df_rh.to_sql('Detalle', conn, if_exists='replace', index=False)

# 5. Comprobamos que la tabla existe y vemos los primeros registros
query_verificacion = "SELECT * FROM Detalle LIMIT 5;"
df_verificacion = pd.read_sql_query(query_verificacion, conn)

# Mostramos el resultado
df_verificacion

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [2]:
query_satisfaccion = """
SELECT 
    "left" AS abandona_empresa, 
    AVG(satisfaction_level) AS nivel_satisfaccion_promedio
FROM Detalle
GROUP BY "left";
"""
df_satisfaccion = pd.read_sql_query(query_satisfaccion, conn)
df_satisfaccion

   abandona_empresa  nivel_satisfaccion_promedio
0                 0                     0.666810
1                 1                     0.440098

In [3]:
query_horas = """
SELECT 
    AVG(average_montly_hours) AS promedio_horas_mensuales
FROM Detalle
WHERE salary IN ('low', 'medium');
"""
df_horas = pd.read_sql_query(query_horas, conn)
df_horas

   promedio_horas_mensuales
0                201.156663

In [4]:
query_fuga_talento = """
SELECT *
FROM Detalle
WHERE promotion_last_5years = 1 AND "left" = 1;
"""
df_fuga_talento = pd.read_sql_query(query_fuga_talento, conn)
df_fuga_talento

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.45,0.51,2,160,3,1,1,1,sales,low
1,0.79,0.59,4,139,3,0,1,1,management,low
2,0.41,0.46,2,160,3,0,1,1,sales,low
3,0.11,0.79,6,292,4,0,1,1,technical,low
4,0.41,0.56,2,154,3,0,1,1,support,medium
5,0.46,0.45,2,138,3,0,1,1,IT,low
6,0.87,1.00,4,258,5,1,1,1,sales,medium
7,0.44,0.55,2,128,3,0,1,1,IT,medium
8,0.45,0.51,2,160,3,1,1,1,sales,low
9,0.79,0.59,4,139,3,0,1,1,management,low
10,0.41,0.46,2,160,3,0,1,1,sales,low
11,0.11,0.79,6,292,4,0,1,1,technical,low
12,0.41,0.56,2,154,3,0,1,1,support,medium
13,0.46,0.45,2,138,3,0,1,1,IT,low
14,0.45,0.51,2,160,3,1,1,1,sales,low
15,0.79,0.59,4,139,3,0,1,1,management,low
16,0.41,0.46,2,160,3,0,1,1,sales,low
17,0.11,0.79,6,292,4,0,1,1,technical,low
18,0.41,0.56,2,154,3,0,1,1,support,medium

In [5]:
query_evaluacion = """
SELECT *
FROM Detalle
WHERE last_evaluation >= 0.9;
"""
df_evaluacion = pd.read_sql_query(query_evaluacion, conn)

# Mostramos cuántos empleados cumplen esta condición y los primeros registros
print(f"Total de empleados con evaluación sobresaliente: {len(df_evaluacion)}")
df_evaluacion.head()

Total de empleados con evaluación sobresaliente: 2988

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.89,1.00,5,224,5,0,1,0,sales,low
1,0.84,0.92,4,234,5,0,1,0,sales,low
2,0.78,0.99,4,255,6,0,1,0,sales,low
3,0.09,0.95,6,304,4,0,1,0,sales,low
4,0.89,0.92,5,242,5,0,1,0,sales,low